version: '2'
services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  odoo14:
    container_name: odoo14
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8091:8069"
    volumes:
      - odoo-odoo14-data:/var/lib/odoo
      - ./config_odoo_14:/etc/odoo
      - ./efishery_addons:/mnt/efishery_addons
    command: odoo --dev=reload

  efishery-sale:
    container_name: efishery-odoo-sale
    image: efishery-odoo-sale:latest
    ports:
      - 8088:8080
    depends_on:
      - odoo14

volumes:
  odoo-odoo14-data:
  odoo-db-data: